name: frontend_flutter

environment:
  sdk: ">=3.7.0 <4.0.0"

version: 1.0.0+1

dependencies:
  firebase_auth: ^3.11.2
  firebase_core: ^1.19.0
  flutter:
    sdk: flutter
  flutter_phosphor_icons: ^0.0.1+6
  fluttertoast: ^8.2.12
  google_fonts: ^6.1.0
  supabase_flutter: ^2.8.4

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/signin_img.png
   - assets/food.png
   - assets/order.png
   - assets/restro2.png
   - assets/Restaurant.png
   - assets/bbq.png
   - assets/peri_peri.png
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
